name: Pull Requests - UnitTests
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: action/pr/unit-tests
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run tests
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Trimarr.xcodeproj
        scheme: Trimarr
        action: test
        destination: 'platform=iOS Simulator,name=iPhone 16'
        parallel-testing-enabled: true
